### ISSUE TITLE
Shutil same file Error during Core.LastStep

### ISSUE THREAD

**Issue by Aphypnise** [fearedbliss/bliss-initramfs#24]
At the LastStep phase, when the program tries to copy the gcc library, the shutil python library raise a samefile error. Seems that the initramfs-generator correctly find the lib, there is just some problem for the copy.

In place of the lib, inside the bi-*/lib64 folder, there is a symlink to the correct lib. 

I tried switching options and python versions (3.7 to 3.6) but nothing changed so well.

Here comes the logs, thanks.

```Features [1]: 2,5

[*] Checking preliminary binaries ...
[*] Creating temporary directory at /home/andy/bliss-initramfs/bi-588119123 ...
[*] Checking required files ...
[+] Using LVM
[*] Copying binaries ...
[*] Copying library dependencies ...
[*] Creating symlinks ...
[*] Performing finishing steps ...
[+] Copying /etc/lvm/lvm.conf from the current system...
Traceback (most recent call last):
  File "./mkinitrd.py", line 59, in <module>
    Main.start()
  File "./mkinitrd.py", line 54, in start
    Core.LastSteps()
  File "/home/andy/bliss-initramfs/pkg/libs/Core.py", line 408, in LastSteps
    cls.CopyLibGccLibrary()
  File "/home/andy/bliss-initramfs/pkg/libs/Core.py", line 430, in CopyLibGccLibrary
    Tools.SafeCopy(libgcc_path, var.llib64)
  File "/home/andy/bliss-initramfs/pkg/libs/Tools.py", line 190, in SafeCopy
    shutil.copy(sourceFile, targetFile)
  File "/usr/lib/python3.7/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/libgcc_s.so.1' and '/home/andy/bliss-initramfs/bi-588119123/lib64/libgcc_s.so.1' are the same file```

**Comment by fearedbliss** [comment]
This project is no longer active. Please fork! Thanks.
